name: Duwuels
version: '${project.version}'
main: me.aroze.duwuels.Duwuels
api-version: 1.18
authors: [ Aroze ]
description: A dogshit duels core
commands:
  duel:
    aliases: [ d, duels, duwuel, duwuels, 1v1, q, queue ]
  gen: {}
  deleteallarenas: {}